### ISSUE TITLE
trouble operating on Windows

### ISSUE THREAD

**Issue by joshudson** [MiruFx/Miru#29]
Sorry to be a busybody but I was curious because somebody besides my own company was using my project besides my own employer.

https://github.com/MiruFx/Miru/blob/a0e99571889dfe2b46bede4b4951a3cc98620ed7/src/Miru/Storages/StorageLinkConsolable.cs

`FileSystem.SymbolicLink` is wrong; should be `FileSystem.File` or `FileSystem.Directory` here. I don't understand what the path is or I'd be able to tell you which. Windows wants to know if the ultimate target is a file or a directory. If the target exits (as it usually does), you can omit the third argument and it will figure it out.

**Comment by joaofx** [comment]
Hey @joshudson!

Thanks a lot for sharing the library and for the tip here. 

Both paths are directories. I definitely must fix it.

Thanks!

**Comment by joaofx** [comment]
Fixed with #30
